version: "3.9"
services:
  database:
    image: postgres:14
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=keyoarbcat
  nodejs-express:
    profiles:
      - nodejs-express
      - compare-frontend
      - js-vue
      - rust-yew
      - rust-yew-solution
    build: ./backend/nodejs/express
    volumes:
      - ./backend/nodejs/express:/code/
    depends_on:
      - database
    expose:
      - "3000"
    ports:
      - "30478:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=keyboardcat
      - SALT_ROUNDS=10
      - DB_CONNECTION=postgresql://postgres:keyoarbcat@database
  rust-yew:
    profiles:
      - nodejs-express
    build: ./frontend/rust/yew
    volumes:
      - ./frontend/rust/yew:/code/
    depends_on:
      - nodejs-express
    expose:
      - "8080"
    ports:
      - "20478:8080"
volumes:
  db-data:
