version: "3.9"
services:
  postgres-db:
    profiles:
      - postgres-db
    image: postgres:14
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  dotnet-aspnet:
    profiles:
      - dotnet-aspnet
    build: ./backend/dotnet/ASP.NET_MVC/TodoAPI_MVC
    volumes:
      - ./backend/dotnet/ASP.NET_MVC/TodoAPI_MVC:/code/
    expose:
      - "5000"
    ports:
      - "30478:5000"
    environment:
      - DB_MODE=${DB_MODE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
  rust-yew:
    profiles:
      - rust-yew
    build: ./frontend/rust/yew
    volumes:
      - ./frontend/rust/yew:/code/
    expose:
      - "8080"
    ports:
      - "20478:8080"
volumes:
  db-data:
