version: "3.9"
services:
  postgres-db:
    image: postgres:14
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  dotnet-aspnet:
    profiles:
      - dotnet-aspnet
    build: ./backend/dotnet/ASP.NET_MVC/TodoAPI_MVC
    expose:
      - "5000"
    ports:
      - "30478:5000"
    environment:
      - TODO_APP_DB_MODE=${DB_MODE}
      - TODO_APP_JWT_SECRET=${JWT_SECRET}
  nodejs-express:
    profiles:
      - nodejs-express
    build: ./backend/nodejs/express
    volumes:
      - ./backend/nodejs/express:/code/
    expose:
      - "3000"
    ports:
      - "30478:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=k${JWT_SECRET}
      - SALT_ROUNDS=10
      - DB_CONNECTION=postgresql://postgres:${DB_PASSWORD}@database
  rust-yew:
    profiles:
      - rust-yew
    build: ./frontend/rust/yew
    volumes:
      - ./frontend/rust/yew:/code/
    expose:
      - "8080"
    ports:
      - "20478:8080"
volumes:
  db-data:
