name: 'Build pull request'

on:
  pull_request:

env:
  Yew-dir: ${{ github.workspace }}/frontend/rust/yew
  Dotnet-dir: ${{ github.workspace }}/backend/dotnet/ASP.NET_MVC/TodoAPI_MVC

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Build backend
    # .NET
    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build .NET
      run: dotnet build -c Release
      working-directory: ${{ env.Dotnet-dir }}

    - name: Run .NET tests
      run: dotnet test -c Release
      working-directory: ${{ env.Dotnet-dir }}

    # Build frontend
    # Yew.rs
    - name: Install stable Cargo toolchain
      uses: actions-rs/toolchain@v1.0.6
      with: 
        toolchain: stable

    - name: Initialize Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: ${{ env.Yew-dir }}

    - name: Install wasm target
      run: rustup target add wasm32-unknown-unknown

    - name: Install trunk
      run: cargo install trunk
      working-directory: ${{ env.Yew-dir }}

    - name: Build Yew
      run: cargo build
      working-directory: ${{ env.Yew-dir }}

    - name: Run Yew tests
      run: cargo test
      working-directory: ${{ env.Yew-dir }}

    - name: Build trunk
      run: trunk build
      working-directory: ${{ env.Yew-dir }}
