name: 'Build and push containers'

on:
  workflow_dispatch:
  push:
    branches: ['main']
    
jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        include:
          - dockerfile: ./backend/dotnet/ASP.NET_MVC/TodoAPI_MVC/Dockerfile
            image: ${{ secrets.AZ_REGISTRY_NAME }}/${{ secrets.AZ_USERNAME }}/TodoAPI_ASPNET
          - dockerfile: ./frontend/rust/yew/Dockerfile
            image: ${{ secrets.AZ_REGISTRY_NAME }}/${{ secrets.AZ_USERNAME }}/TodoUI_YEW

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Azure container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AZ_REGISTRY_NAME }}
          username: ${{ secrets.AZ_USERNAME }}
          password: ${{ secrets.AZ_PASSWORD }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}