name: 'Release'

on:
  workflow_dispatch:
    inputs:
      pull_delay_s:
        description: 'Time to wait for pull to complete'
        type: string
        required: true
        default: '30'
      delete_volume:
        description: 'Delete database volume'
        type: boolean
        required: true
        default: false
  
env:
  pull: |
    cd ~/source/repos/${{ github.event.repository.name }}
    git reset --hard
    git pull
    sleep ${{ github.event.inputs.pull_delay_s }}
    echo "DB_USER=${{ secrets.DB_USER }}" >> .env
    echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
    echo "DB_MODE=${{ secrets.DB_MODE }}" >> .env
    echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

  compose_soft: |
    docker stop $(docker ps -a -q)
    docker rm $(docker ps -a -q)
    docker image rm $(docker images -a -q)
    docker compose --profile postgres --profile dotnet-aspnet --profile rust-yew up --remove-orphans

  compose_hard: |
    docker stop $(docker ps -a -q)
    docker rm $(docker ps -a -q)
    docker image rm $(docker images -a -q)
    docker volume rm ${{ github.event.repository.name }}_db-data
    docker compose --profile postgres --profile dotnet-aspnet --profile rust-yew up --remove-orphans

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Pull repo on mikr.us ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: ${{ env.pull }}
        command_timeout: 30m

    - if: github.event.inputs.delete_volume == 'false'
      name: Perform soft compose on mikr.us ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: ${{ env.pull-and-compose }}
        command_timeout: 30m

    - if: github.event.inputs.delete_volume == 'true'
      name: Perform hard compose on mikr.us ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: ${{ env.pull-and-compose }}
        command_timeout: 30m
