name: 'Release'

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Select deploy target'
        type: choice
        options:
        - 'mikr.us'
        - 'Azure VM'
        required: true
        default: 'Azure VM'
      delete_volume:
        description: 'Delete database volume'
        type: boolean
        required: true
        default: false

jobs:
  push-containers:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Push containers to registry
      uses: ./.github/workflows/push-containers.yml@main

    - name: Read docker-compose.yml
      id: compose_contents
      uses: juliangruber/read-file-action@v1
      with:
        path: ./docker-compose.yml

    - if: github.event.inputs.target == 'mikr.us'
      name: Deploy to mikr.us
      uses: ./.github/workflows/deploy-mikrus.yml@main
      with:
        delete_volume: ${{ github.event.inputs.delete_volume }}
        compose_contents: ${{ github.steps.compose_contents.content }}

    - if: github.event.inputs.target == 'Azure VM'
      name: Deploy to Azure
      uses: ./.github/workflows/deploy-azure.yml@main
      with:
        delete_volume: ${{ github.event.inputs.delete_volume }}
        compose_contents: ${{ github.steps.compose_contents.content }}
