name: 'Release'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
env:
  pull-and-compose: |
    cd ~/source/repos/${{ github.event.repository.name }}
    git reset --hard
    git pull
    echo "DB_USER=${{ secrets.DB_USER }}" >> .env
    echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
    echo "DB_MODE=${{ secrets.DB_MODE }}" >> .env
    echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
    docker stop $(docker ps -a -q)
    docker rm $(docker ps -a -q)
    docker compose --profile postgres-db --profile dotnet-aspnet --profile rust-yew up --remove-orphans

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Connect to mikr.us ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: ${{ env.pull-and-compose }}
        command_timeout: 30m
